import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSearch, faSortDesc } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <section className=" relative">
          <div className=" fixed  top-0 left-0 h-12 w-full bg-black">
            <div className=" flex items-center justify-between">
              <div className="left">
                <ul className=" flex">
                  <li className=" px-4 py-3 cursor-pointer group hover:bg-slate-700">
                    <Link
                      href=""
                      className="  cursor-pointer group-hover:text-slate-300 text-white"
                    >
                      HOME
                    </Link>
                  </li>
                  <li className=" px-4 py-3 cursor-pointer group hover:bg-slate-700 ">
                    <Link
                      href=""
                      className="  cursor-pointer group-hover:text-slate-300 text-white"
                    >
                      BAND
                    </Link>
                  </li>
                  <li className=" px-4 py-3 cursor-pointer group hover:bg-slate-700">
                    <Link
                      href=""
                      className="  cursor-pointer group-hover:text-slate-300 text-white"
                    >
                      TOUR
                    </Link>
                  </li>
                  <li className=" px-4 py-3 cursor-pointer group hover:bg-slate-700">
                    <Link
                      href=""
                      className="  cursor-pointer group-hover:text-slate-300 text-white"
                    >
                      CONTACT
                    </Link>
                  </li>
                  <li className=" h-11 w-24 relative cursor-pointer group hover:bg-slate-700">
                    <div className=" absolute top-3 left-3">
                      <Link
                        href=""
                        className="  cursor-pointer group-hover:text-slate-100   text-white flex  space-x-2"
                      >
                        MORE
                        <FontAwesomeIcon
                          className="h-4 w-4 text-white"
                          icon={faSortDesc}
                        />
                      </Link>
                    </div>
                    <div className=" h-auto  w-40 hidden absolute top-[46px] group-hover:block bg-slate-100">
                      <ul className=" flex flex-col">
                        <li className=" pl-3 cursor-pointer py-3 hover:bg-slate-300">
                          <Link href="">Merchandise</Link>
                        </li>
                        <li className=" pl-3  cursor-pointer py-3 hover:bg-slate-300">
                          <Link href="">Extras</Link>
                        </li>
                        <li className=" pl-3 cursor-pointer py-3 hover:bg-slate-300">
                          <Link href="">Media</Link>
                        </li>
                      </ul>
                    </div>
                  </li>
                </ul>
              </div>
              <div className="right px-6 py-4 hover:bg-red-500 cursor-pointer">
                <FontAwesomeIcon
                  icon={faSearch}
                  className="   h-3 w-3 text-white"
                />
              </div>
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
